name: Verify Docker image(s)

defaults:
  run:
    shell: "bash -o errexit -o nounset -o pipefail {0}"

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build --file ./${{ matrix.distro }}/Dockerfile --tag oscarotero/lume:latest ./
    strategy:
      matrix:
        distro:
          - alpine
          - centos
          - debian
          - ubuntu

on:
  pull_request:
    branches:
      - main
